config/routes.rb
Rails.application.routes.draw do
  resources :surveys

    root "surveys#new"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/survey.rb
class Survey < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: [:show, :edit, :update, :destroy]

  # GET /surveys
  # GET /surveys.json
  def index
    @surveys = Survey.all
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
  end

  # GET /surveys/new
  def new
    @survey = Survey.new
  end

  # GET /surveys/1/edit
  def edit
  end

  # POST /surveys
  # POST /surveys.json
  def create
    @survey = Survey.new(survey_params)

    respond_to do |format|
      if @survey.save
        format.html { redirect_to @survey, notice: 'Survey was successfully created.' }
        format.json { render :show, status: :created, location: @survey }
      else
        format.html { render :new }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surveys/1
  # PATCH/PUT /surveys/1.json
  def update
    respond_to do |format|
      if @survey.update(survey_params)
        format.html { redirect_to @survey, notice: 'Survey was successfully updated.' }
        format.json { render :show, status: :ok, location: @survey }
      else
        format.html { render :edit }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @survey.destroy
    respond_to do |format|
      format.html { redirect_to surveys_url, notice: 'Survey was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @survey = Survey.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survey_params
      params.require(:survey).permit(:school, :duration, :hotel, :tailgating, :taillocation, :bar_friday, :after_bar_saturday, :kappa, :beta, :age)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CortacaSurvey</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/surveys/_form.html.erb
<%= form_with(model: survey, local: true) do |form| %>
  <% if survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
      <% survey.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :school %>
    <%= form.text_field :school %>
  </div>

  <div class="field">
    <%= form.label :duration %>
    <%= form.text_field :duration %>
  </div>

  <div class="field">
    <%= form.label :hotel %>
    <%= form.text_field :hotel %>
  </div>

  <div class="field">
    <%= form.label :tailgating %>
    <%= form.text_field :tailgating %>
  </div>

  <div class="field">
    <%= form.label :taillocation %>
    <%= form.text_area :taillocation %>
  </div>

  <div class="field">
    <%= form.label :bar_friday %>
    <%= form.text_area :bar_friday %>
  </div>

  <div class="field">
    <%= form.label :after_bar_saturday %>
    <%= form.text_area :after_bar_saturday %>
  </div>

  <div class="field">
    <%= form.label :kappa %>
    <%= form.text_field :kappa %>
  </div>

  <div class="field">
    <%= form.label :beta %>
    <%= form.text_field :beta %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/surveys/edit.html.erb
<h1>Editing Survey</h1>

<%= render 'form', survey: @survey %>

<%= link_to 'Show', @survey %> |
<%= link_to 'Back', surveys_path %>

app/views/surveys/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Surveys</h1>

<table>
  <thead>
    <tr>
      <th>School</th>
      <th>Duration</th>
      <th>Hotel</th>
      <th>Tailgating</th>
      <th>Taillocation</th>
      <th>Bar friday</th>
      <th>After bar saturday</th>
      <th>Kappa</th>
      <th>Beta</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @surveys.each do |survey| %>
      <tr>
        <td><%= survey.school %></td>
        <td><%= survey.duration %></td>
        <td><%= survey.hotel %></td>
        <td><%= survey.tailgating %></td>
        <td><%= survey.taillocation %></td>
        <td><%= survey.bar_friday %></td>
        <td><%= survey.after_bar_saturday %></td>
        <td><%= survey.kappa %></td>
        <td><%= survey.beta %></td>
        <td><%= survey.age %></td>
        <td><%= link_to 'Show', survey %></td>
        <td><%= link_to 'Edit', edit_survey_path(survey) %></td>
        <td><%= link_to 'Destroy', survey, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Survey', new_survey_path %>

app/views/surveys/new.html.erb
<h1>I'm Going to Cortaca! - Meadowlands 11/16/19</h1>

<%= render 'form', survey: @survey %>

<%= link_to 'Back', surveys_path %>

app/views/surveys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>School:</strong>
  <%= @survey.school %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @survey.duration %>
</p>

<p>
  <strong>Hotel:</strong>
  <%= @survey.hotel %>
</p>

<p>
  <strong>Tailgating:</strong>
  <%= @survey.tailgating %>
</p>

<p>
  <strong>Taillocation:</strong>
  <%= @survey.taillocation %>
</p>

<p>
  <strong>Bar friday:</strong>
  <%= @survey.bar_friday %>
</p>

<p>
  <strong>After bar saturday:</strong>
  <%= @survey.after_bar_saturday %>
</p>

<p>
  <strong>Kappa:</strong>
  <%= @survey.kappa %>
</p>

<p>
  <strong>Beta:</strong>
  <%= @survey.beta %>
</p>

<p>
  <strong>Age:</strong>
  <%= @survey.age %>
</p>

<%= link_to 'Edit', edit_survey_path(@survey) %> |
<%= link_to 'Back', surveys_path %>